var searchData=
[
  ['xwlua操作系统的capi库_0',['XWLUA操作系统的CAPI库',['../group__xwlua__xwos.html',1,'']]],
  ['xwlua虚拟机的capi库_1',['XWLUA虚拟机的CAPI库',['../group__xwlua__xwvm.html',1,'']]],
  ['xwlua设备栈的capi库_2',['XWLUA设备栈的CAPI库',['../group__xwlua__xwds.html',1,'']]],
  ['xwlua_3',['XWLUA',['../group__xwlua.html',1,'']]],
  ['xwos中间件_4',['XWOS中间件',['../group__xwmd.html',1,'']]],
  ['xwos内存管理通用定义_5',['XWOS内存管理通用定义',['../group__xwmm__common.html',1,'']]],
  ['xwos内存管理_6',['XWOS内存管理',['../group__xwmm.html',1,'']]],
  ['xwos内核_7',['XWOS内核',['../group__xwos.html',1,'']]],
  ['xwos的同步机制_8',['XWOS的同步机制',['../group__xwos__sync.html',1,'']]],
  ['xwos的基本类型_9',['XWOS的基本类型',['../group__xwos__lib__type.html',1,'']]],
  ['xwos的对象_10',['XWOS的对象',['../group__xwos__lib__xwobj.html',1,'']]],
  ['xwos的时间类型_11',['XWOS的时间类型',['../group__xwos__lib__type__time.html',1,'']]],
  ['xwos的标准头文件_12',['XWOS的标准头文件',['../group__xwos__standard.html',1,'']]],
  ['xwos的版本号_13',['XWOS的版本号',['../group__xwos__version.html',1,'']]],
  ['xwos的设备栈_14',['XWOS的设备栈',['../group__xwcd__ds.html',1,'']]],
  ['xwos的通用库_15',['XWOS的通用库',['../group__xwos__lib.html',1,'']]],
  ['xwos的通讯机制_16',['XWOS的通讯机制',['../group__xwmd__isc.html',1,'']]],
  ['xwos的锁_17',['XWOS的锁',['../group__xwos__lock.html',1,'']]]
];
